### ISSUE TITLE
bigobj causes compilation error on MSVC

### ISSUE THREAD

**Issue by alighadyali** [xR3b0rn/dbcppp#133]
Compiling with MSVC 19.35. Fails with the error below. 

`E:\work\*path*\build\debug\_deps\libdbcppp-build\third-party\libxml2 -DWIN32 -D_DEBUG   /bigobj /fo _deps\libdbcppp-build\third-party\libxml2\CMakeFiles\LibXml2.dir\win32\libxml2.rc.res E:\*path*\build\debug\_deps\libdbcppp-src\third-party\libxml2\win32\libxml2.rc
fatal error RC1106: invalid option: /bigobj`

The error can be fixed by replacing 

`add_definitions("/bigobj") to add_compile_options("/bigobj") `
on line 15 in the project cmake file.

**Comment by alighadyali** [comment]
I had a typo in my fix. It should be add_compile_options("/bigobj")

**Comment by xR3b0rn** [comment]
Actually I think this flag is not needed anymore, can you try to compile the library by just removing the flag?

**Comment by alighadyali** [comment]
Yes, seems to work just fine if it’s commented out. I have not tested the library functionality though.

**Comment by xR3b0rn** [comment]
I once added this flag, since for an older verison of the library, the MSVC compiler ran out of memory while compiling the library when using the default settings, while `g++` and `clang` seemed to not care about anything. So when you are able to compile the library without the flag, we can be sure the flag is not needed anymore.

**Comment by xR3b0rn** [comment]
If you confirm my assumtion, I can remove the flag.

**Comment by alighadyali** [comment]
Yes, everything seems to be working without the flag.
