### ISSUE TITLE
Remove boost dependencies of non header only libraries, extract required boost-headers and switch to boost::spirit::x3

### ISSUE THREAD

**Issue by xR3b0rn** [xR3b0rn/dbcppp#44]

**Comment by ngbrown** [comment]
Instead of writing a parser from scratch, probably better to use one that can generate self-contained code. In Python, I've been using a dbc parser based on [ply](https://github.com/dabeaz/ply), a lex/yacc based parser. I know of a code generator inspired by ply for c# . There might be something similar for c++. If not, is it really that big of a burden to include boost? A customized subset can be generated and included in-tree.

**Comment by xR3b0rn** [comment]
Thanks for the hint. I think I will try to remove all non header only boost libraries, extract the required boost-headers for spirit + switch to x3.

**Comment by xR3b0rn** [comment]
Added required boost headers to the project: bda3eb862f4d5192b8e33bf21dcfa97ef4737b6a
Moved from boost::spirit::qi to boost::spirit::x3: e65e657c97feb402657940f332aaec0932066dc2
