### ISSUE TITLE
KCD xml schema is LGPL

### ISSUE THREAD

**Issue by mf01** [xR3b0rn/dbcppp#78]
In [src/libdbcppp/KcdXsd.cpp](https://github.com/xR3b0rn/dbcppp/blob/v3.0.1-stable-api/src/libdbcppp/KcdXsd.cpp) there is the KCD XML schema hard coded. This XML schema is LGPL licenced. In my opinion libdbcppp inherit the LGPL licence. Due to dynamic linkaage this would be ok, but it is a pitfall because the project dbcppp advertises  a MIT licence.

**Comment by xR3b0rn** [comment]
Thanks for the hint. I will check how I have to handle this correctly.

**Comment by mf01** [comment]
I have some proposals:

- use the XML schema as file. Solves the licence issue but introduce an additional file which msut be handled (by the user)
- Compile KCD support optionally.  The rest of the lib without KCD is still MIT. But this result in different licences for different builds.
- Find a XML with other licence....

I would recommend a licence hint in the Readme until this issue is solved.

**Comment by xR3b0rn** [comment]
Just for the record: I remember that I have checked the license conditions, however it seems like I missunderstood the part which specifies how the XSD may be distributed. I added a notice at the end of README.md.

In order to fix the issue the XSD shall be placed in a .xsd file. Subsequently, the XSD shall be installed along the library.

Thank you again.
