### ISSUE TITLE
Build sys improvement

### ISSUE THREAD

**Issue by simutisernestas** [xR3b0rn/dbcppp#92]
Would you be interested in accepting a PR improving build system so that it would create cmake config file and library could be found in packages that use it by calling cmake `find_package` function?

Also, with very little effort I can make it compile the code with dynamically link-able version of `libxml2` (form `apt` in my case). I was wondering why do you have it as submodule and compile it together with `dbcppp`? I think removing this would make the lib more portable.

**Comment by xR3b0rn** [comment]
Of course I would accept such PR.

The reason why I added `libxml2` as submodule is because I wanted to make the library as easy as possible to build and install. I rather could think of making this optional, e.g.: only if a -DWITH-LIBXML2=<Path to libxml> or something like that is specified, the local version of `libxml2` is used, elsewise the `libxml2`-version shipped with this repo is used. What do you think?
